version: '2.6'

services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: python -m uvicorn main:app --reload --host 0.0.0.0
    volumes:
      - .:/proj
    ports:
      - "0.0.0.0:8000:8000"
    expose:
      - 8000
    depends_on:
      - db
  db:
    hostname: postgres
    image: postgres:14.2
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
  pgadmin:
    image: dpage/pgadmin4:6.5
    environment:
        PGADMIN_DEFAULT_EMAIL: admin@admin.com
        PGADMIN_DEFAULT_PASSWORD: root
    ports:
        - "5050:80"
    depends_on:
        - db
